title: shrimp chips
description: Digital Sanctuary.
permalink: /artifacts/:title/
baseurl: ""
url: "https://shrimplines.github.io"
exclude: [README.md, Gemfile, Gemfile.lock, .github]
kramdown:
  input: GFM
