# Site Settings
title: Circles
description: My digital hole

# Build Settings
exclude: [README.md, Gemfile, Gemfile.lock, .github]

# URL Settings
baseurl: ""
url: "https://shrimplines.github.io"

# Markdown Settings
kramdown:
  input: GFM
