encoding: utf-8
title: "shrimp chips"
description: "My digital hole."

sass:
  style: compressed
  sass_dir: _sass 

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - vendor
  - node_modules
  - .vercel

baseurl: ""
url: "https://shrimplines.github.io"

kramdown:
  input: GFM
  syntax_highlighter: rouge
